export const SET_HOME_IMAGE = 'SET_HOME_IMAGE';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM'
export const SET_COOKIE_IMAGE = 'SET_COOKIE_IMAGE'
export const ADD_TEAM_ITEM = 'ADD_TEAM_ITEM'
export const REMOVE_TEAM_ITEM = 'REMOVE_TEAM_ITEM'
export const EMPTY_CART = "EMPTY_CART"
export const EMPTY_COMMENT = "EMPTY_COMMENT"
export const EMPTY_COMMENT2 = "EMPTY_COMMENT2"


// FEED FIREBASE COOKIES
export const BEGIN_COOKIES_FEED = "BEGIN_COOKIES_FEED";
export const SUCCESS_COOKIES_FEED = "SUCCESS_COOKIES_FEED";
export const FAIL_COOKIES_FEED = "FAIL_PRFAIL_COOKIES_FEEDODUCTS_REQUEST";

// REQUEST FIREBASE COOKIES
export const BEGIN_COOKIES_REQUEST = "BEGIN_COOKIES_REQUEST";
export const SUCCESS_COOKIES_REQUEST = "SUCCESS_COOKIES_REQUEST";
export const FAIL_COOKIES_REQUEST = "FAIL_COOKIES_REQUEST";


// REQUEST FIREBASE LOGIN
export const BEGIN_LOGIN_REQUEST = "BEGIN_LOGIN_REQUEST";
export const SUCCESS_LOGIN_REQUEST = "SUCCESS_LOGIN_REQUEST";
export const FAIL_LOGIN_REQUEST = "FAIL_LOGIN_REQUEST";
export const REMEMBER_LOGIN = "REMEMBER_LOGIN";

// REQUEST FIREBASE REGISTER
export const BEGIN_REGISTER_REQUEST = "BEGIN_REGISTER_REQUEST";
export const SUCCESS_REGISTER_REQUEST = "SUCCESS_REGISTER_REQUEST";
export const FAIL_REGISTER_REQUEST = "FAIL_REGISTER_REQUEST";

// UPDATE USER INFO
export const BEGIN_UPDATE_USERINFO = "BEGIN_UPDATE_USERINFO";
export const SUCCESS_UPDATE_USERINFO = "SUCCESS_UPDATE_USERINFO";
export const FAIL_UPDATE_USERINFO = "FAIL_UPDATE_USERINFO";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

// CREATE ORDER
export const BEGIN_ORDER_CREATE = 'BEGIN_ORDER_CREATE';
export const SUCCESS_ORDER_CREATE = 'SUCCESS_ORDER_CREATE';
export const FAIL_ORDER_CREATE = 'FAIL_ORDER_CREATE';
export const RESET_ORDER = 'RESET_ORDER';

// PAY ORDER
export const BEGIN_ORDER_PAY = 'BEGIN_ORDER_PAY';
export const SUCCESS_ORDER_PAY = 'SUCCESS_ORDER_PAY';
export const FAIL_ORDER_PAY = 'FAIL_ORDER_PAY';
export const RESET_ORDER_PAY = 'RESET_ORDER_PAY';

// CREATE COMMENT
export const BEGIN_COMMENT_CREATE = 'BEGIN_COMMENT_CREATE';
export const SUCCESS_COMMENT_CREATE = 'SUCCESS_COMMENT_CREATE';
export const FAIL_COMMENT_CREATE = 'FAIL_COMMENT_CREATE';
export const RESET_COMMENT = 'RESET_COMMENT';
export const FEED_TO_COMMENTITEM='FEED_TO_COMMENTITEM'

// CREATE COMMENT2
export const BEGIN_COMMENT2_CREATE = 'BEGIN_COMMENT2_CREATE';
export const SUCCESS_COMMENT2_CREATE = 'SUCCESS_COMMENT2_CREATE';
export const FAIL_COMMENT2_CREATE = 'FAIL_COMMENT2_CREATE';
export const RESET_COMMENT2 = 'RESET_COMMENT2';
export const FEED_TO_COMMENTITEM2='FEED_TO_COMMENTITEM2'

// GET ORDER DETAIL
export const BEGIN_ORDER_DETAIL = 'BEGIN_ORDER_DETAIL';
export const SUCCESS_ORDER_DETAIL = 'SUCCESS_ORDER_DETAIL';
export const FAIL_ORDER_DETAIL = 'FAIL_ORDER_DETAIL';

// GET COMMENT DETAIL
export const BEGIN_COMMENT_DETAIL = 'BEGIN_COMMENT_DETAIL';
export const SUCCESS_COMMENT_DETAIL = 'SUCCESS_COMMENT_DETAIL';
export const FAIL_COMMENT_DETAIL = 'FAIL_COMMENT_DETAIL';

// GET COMMENT2 DETAIL
export const BEGIN_COMMENT2_DETAIL = 'BEGIN_COMMENT2_DETAIL';
export const SUCCESS_COMMENT2_DETAIL = 'SUCCESS_COMMENT2_DETAIL';
export const FAIL_COMMENT2_DETAIL = 'FAIL_COMMENT2_DETAIL';

export const GET_ORDER_BY_USER = 'GET_ORDER_BY_USER';
export const GET_ORDER_ITEM_BY_USER= 'GET_ORDER_ITEM_BY_USER';
export const REMOVE_ORDER_ITEM='REMOVE_ORDER_ITEM'
