export const SET_HOME_IMAGE = 'SET_HOME_IMAGE';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM'
export const SET_COOKIE_IMAGE = 'SET_COOKIE_IMAGE'
export const ADD_TEAM_ITEM = 'ADD_TEAM_ITEM'
export const REMOVE_TEAM_ITEM = 'REMOVE_TEAM_ITEM'